// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6icSLuRoC8WK5yHxTKL4TTtMAPm20IWg',
    appId: '1:114621335348:web:0d9ed8ffb4dbd84dcd4761',
    messagingSenderId: '114621335348',
    projectId: 'mycoolnoteesapp',
    authDomain: 'mycoolnoteesapp.firebaseapp.com',
    storageBucket: 'mycoolnoteesapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAel8rmK9iOBfTMJpMUKgHQQCx9ZHyqSjk',
    appId: '1:114621335348:android:217246c495982d94cd4761',
    messagingSenderId: '114621335348',
    projectId: 'mycoolnoteesapp',
    storageBucket: 'mycoolnoteesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEy4JqwyUHOyvhEt84ZatAFcFd6hkM8gI',
    appId: '1:114621335348:ios:caefc0f51dfe8315cd4761',
    messagingSenderId: '114621335348',
    projectId: 'mycoolnoteesapp',
    storageBucket: 'mycoolnoteesapp.appspot.com',
    iosClientId: '114621335348-bema9ahdld2f1avcnmv7gd05m6d35s0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
